### ISSUE TITLE
Bug: crashes on multiple searches?

### ISSUE THREAD

**Issue by redragonx** [rabbitfighter81/WordSleuth-Android#21]
Process: com.rabbitfighter.swipenavexample, PID: 1972
    java.lang.RuntimeException: An error occured while executing doInBackground()
            at android.os.AsyncTask$3.done(AsyncTask.java:304)
            at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
            at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
            at java.util.concurrent.FutureTask.run(FutureTask.java:242)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.NullPointerException: asset
            at android.content.res.AssetManager.getAssetRemainingLength(Native Method)
            at android.content.res.AssetManager.access$300(AssetManager.java:36)
            at android.content.res.AssetManager$AssetInputStream.available(AssetManager.java:561)
            at java.io.InputStreamReader.read(InputStreamReader.java:221)
            at java.io.BufferedReader.fillBuf(BufferedReader.java:145)
            at java.io.BufferedReader.readLine(BufferedReader.java:397)
            at com.rabbitfighter.wordsleuth.Services.BoundSearchService.searchDictionary(BoundSearchService.java:129)
            at com.rabbitfighter.wordsleuth.Activities.SearchActivity$AsyncSearchTask.doInBackground(SearchActivity.java:311)
            at com.rabbitfighter.wordsleuth.Activities.SearchActivity$AsyncSearchTask.doInBackground(SearchActivity.java:302)
            at android.os.AsyncTask$2.call(AsyncTask.java:292)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
07-05 14:48:52.660    1972-1972/? E/ActivityThread﹕ Activity com.rabbitfighter.wordsleuth.Activities.SearchActivity has leaked ServiceConnection com.rabbitfighter.wordsleuth.Activities.SearchActivity$2@148d090 that was originally bound here
    android.app.ServiceConnectionLeaked: Activity com.rabbitfighter.wordsleuth.Activities.SearchActivity has leaked ServiceConnection com.rabbitfighter.wordsleuth.Activities.SearchActivity$2@148d090 that was originally bound here
            at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1077)
            at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:971)
            at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1774)
            at android.app.ContextImpl.bindService(ContextImpl.java:1757)
            at android.content.ContextWrapper.bindService(ContextWrapper.java:539)
            at com.rabbitfighter.wordsleuth.Activities.SearchActivity.onCreate(SearchActivity.java:107)
            at android.app.Activity.performCreate(Activity.java:5990)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390)
            at android.app.ActivityThread.access$800(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5257)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by redragonx** [comment]
Fixed
